"""ScriptMerger — Merge Layer (L4)

Assembles the final Python script from translated partitions.
"""

from __future__ import annotations

import ast
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from uuid import uuid4

import structlog

from partition.merge.dependency_injector import (
    add_cross_file_stubs,
    build_name_registry,
    inject_variable_names,
)
from partition.merge.import_consolidator import consolidate_imports

log = structlog.get_logger(__name__)

_IMPORT_PREFIXES = ("import ", "from ")


def _strip_imports(code: str) -> str:
    """Remove top-level import/from lines from a code block.

    Continuation lines (ending with backslash or inside parentheses) are also
    removed so the consolidated import block at the top is the single source.
    """
    lines = code.splitlines()
    result: list[str] = []
    skip_continuation = False
    open_parens = 0

    for line in lines:
        stripped = line.strip()

        if skip_continuation:
            open_parens += stripped.count("(") - stripped.count(")")
            if open_parens <= 0 and not stripped.endswith("\\"):
                skip_continuation = False
                open_parens = 0
            continue

        if any(stripped.startswith(p) for p in _IMPORT_PREFIXES):
            open_parens = stripped.count("(") - stripped.count(")")
            if stripped.endswith("\\") or open_parens > 0:
                skip_continuation = True
            continue

        result.append(line)

    # Drop leading blank lines left after import removal
    while result and not result[0].strip():
        result.pop(0)

    return "\n".join(result)


def _make_header(
    source_path: str,
    block_count: int,
    partial_count: int,
    target_runtime: str,
) -> str:
    """Generate the header comment for the merged script."""
    now = datetime.now(timezone.utc).isoformat()
    return textwrap.dedent(f"""\
        # ============================================================
        # Auto-generated by SAS→Python Conversion Accelerator
        # Source: {source_path}
        # Generated: {now}
        # Target: {target_runtime}
        # Blocks: {block_count} total, {partial_count} partial
        # ============================================================
    """)


def _make_todo_stub(partition: dict) -> str:
    """Create a structured TODO stub for HUMAN_REVIEW or FAILED blocks."""
    partition_type = partition.get("partition_type", "UNKNOWN")
    line_start = partition.get("line_start", "?")
    line_end = partition.get("line_end", "?")
    raw_sas = partition.get("raw_code", partition.get("source_code", ""))

    sas_commented = "\n".join(f"#   {line}" for line in raw_sas.split("\n")[:20])
    if len(raw_sas.split("\n")) > 20:
        sas_commented += "\n#   ... (truncated)"

    return (
        f"# TODO: HUMAN_REVIEW — {partition_type} "
        f"(lines {line_start}–{line_end})\n"
        f"# Original SAS code:\n"
        f"{sas_commented}\n"
        f"# END TODO"
    )


def merge_script(
    conversion_results: list[dict],
    partitions: list[dict],
    source_file_id: str,
    source_path: str,
    target_runtime: str = "python",
    output_dir: str = "output",
    unresolved_refs: list[str] | None = None,
    cross_file_sources: dict[str, str] | None = None,
) -> dict:
    """Assemble the final Python script from translated partitions.

    Returns a MergedScript dict with script text, metadata, and output path.
    """
    # 1. Sort by line_start
    paired = list(zip(conversion_results, partitions))
    paired.sort(key=lambda p: p[1].get("line_start", 0))

    # 2. Consolidate imports — combine LLM-detected module names with imports
    #    parsed directly from each block's code (covers fallback paths where
    #    imports_detected is []).
    all_imports: list[list[str]] = []
    for cr in conversion_results:
        detected = list(cr.get("imports_detected", []) or [])
        # Also parse inline import lines from the raw code
        for line in (cr.get("python_code", "") or "").splitlines():
            stripped = line.strip()
            if stripped.startswith("import "):
                module = stripped[len("import ") :].split()[0].split(".")[0]
                if module not in detected:
                    detected.append(module)
            elif stripped.startswith("from "):
                parts = stripped.split()
                if len(parts) >= 2:
                    module = parts[1].split(".")[0]
                    if module not in detected:
                        detected.append(module)
        all_imports.append(detected)
    import_block = consolidate_imports(all_imports)

    # 3. Build name registry
    registry = build_name_registry(partitions, source_file_id)

    # 4. Assemble body
    body_parts: list[str] = []
    partial_count = 0
    human_review_count = 0

    for cr, partition in paired:
        status = cr.get("status", "SUCCESS")
        if status in ("HUMAN_REVIEW", "FAILED"):
            body_parts.append(_make_todo_stub(partition))
            if status == "HUMAN_REVIEW":
                human_review_count += 1
            continue

        if status == "PARTIAL":
            partial_count += 1

        code = cr.get("python_code", "")
        code = _strip_imports(code)
        code = inject_variable_names(code, registry, source_file_id)
        body_parts.append(code)

    # 5. Add cross-file stubs
    body_text = "\n\n".join(body_parts)
    if unresolved_refs:
        body_text = add_cross_file_stubs(body_text, unresolved_refs, cross_file_sources or {})

    # 6. Build final script
    header = _make_header(source_path, len(conversion_results), partial_count, target_runtime)
    final_script = f"{header}\n{import_block}\n\n\n{body_text}\n"

    # 7. ast.parse() validation
    syntax_valid = True
    syntax_errors: list[str] = []
    try:
        ast.parse(final_script)
    except SyntaxError as e:
        syntax_valid = False
        syntax_errors.append(f"Line {e.lineno}: {e.msg}")
        log.warning("merged_script_syntax_error", error=str(e), file=source_path)

    # 8. Determine status
    if not syntax_valid:
        merge_status = "FAILED"
    elif partial_count > 0 or human_review_count > 0:
        merge_status = "HAS_GAPS"
    else:
        merge_status = "SUCCESS"

    # 9. Write output
    suffix = "_converted.py"
    stem = Path(source_path).stem
    output_path = Path(output_dir) / f"{stem}{suffix}"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(final_script, encoding="utf-8")

    log.info(
        "script_merged",
        file=source_path,
        blocks=len(conversion_results),
        partial=partial_count,
        human_review=human_review_count,
        syntax_valid=syntax_valid,
        status=merge_status,
    )

    return {
        "script_id": str(uuid4()),
        "source_file_id": source_file_id,
        "python_script": final_script,
        "import_block": import_block,
        "block_count": len(conversion_results),
        "partial_count": partial_count,
        "human_review_count": human_review_count,
        "syntax_valid": syntax_valid,
        "syntax_errors": syntax_errors,
        "status": merge_status,
        "output_path": str(output_path),
        "trace_id": str(uuid4()),
        "created_at": datetime.now(timezone.utc).isoformat(),
    }
