# ============================================================
# Auto-generated by SAS→Python Conversion Accelerator
# Source: C:\Users\labou\Desktop\Stage\backend\knowledge_base\gold_standard\gs_01_basic_data_step.sas
# Generated: 2026-04-02T09:24:56.727202+00:00
# Target: python
# Blocks: 2 total, 1 partial
# ============================================================

import numpy as np
import pandas as pd


# Import necessary libraries
import pandas as pd
# Set display options for pandas
display_options = {'display.max_rows': None, 'display.max_columns': None}
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
# Note: There is no direct equivalent to SAS options MPRINT and SYMBOLGEN in Python.
# The above code sets display options for pandas, but does not directly translate the SAS options.

# PARTIAL: Validation failed (RuntimeError: __import__ not found)
import pandas as pd
import numpy as np
# Load the sashelp.class dataset into a pandas DataFrame
sashelp_class = pd.read_csv('sashelp_class.csv')

# Create a new column 'full_name' by concatenating 'name' and 'Employee'
# The LENGTH statement in SAS is not directly applicable in Python, so it is omitted
sashelp_class['full_name'] = sashelp_class['name'].astype(str) + ' Employee'

# Create a new column 'age_group' based on the 'age' column
# The IFC function in SAS is equivalent to the np.where function in numpy
sashelp_class['age_group'] = np.where(sashelp_class['age'] >= 14, 'Senior', 'Junior')

# Create a new column 'bmi' by calculating weight / (height**2) * 703
# The ** operator in SAS is equivalent to the ** operator in Python
sashelp_class['bmi'] = sashelp_class['weight'] / (sashelp_class['height']**2) * 703

# Select the required columns
employees = sashelp_class[['name', 'full_name', 'age', 'age_group', 'bmi']]

