# ============================================================
# Auto-generated by SAS→Python Conversion Accelerator
# Source: C:\Users\labou\AppData\Local\Temp\pytest-of-labou\pytest-12\test_merge_results_is_list0\test.sas
# Generated: 2026-03-31T22:40:45.858176+00:00
# Target: python
# Blocks: 2 total, 2 partial
# ============================================================




# PARTIAL: Translation failed after 3 retries
# Original SAS:
# DATA work.out;
# SET sashelp.class;
# age_group = PUT(Age, 3.);
# IF Age > 14 THEN flag = 1;
# ELSE flag = 0;
# RUN;

# PARTIAL: Translation failed after 3 retries
# Original SAS:
# PROC MEANS DATA=work.out NWAY NOPRINT;
# CLASS flag;
# VAR Age;
# OUTPUT OUT=work.summary MEAN=avg_age;
# RUN;
