/* gs_41 - GLOBAL statements: OPTIONS, LIBNAME, TITLE, FOOTNOTE */
OPTIONS MPRINT SYMBOLGEN MLOGIC FULLSTIMER;
LIBNAME raw '/data/raw' ACCESS=READONLY;
LIBNAME work '/data/work';
LIBNAME output '/data/output';

TITLE1 'Quarterly Financial Report';
TITLE2 'Period: Q1 2025';
FOOTNOTE 'Generated by SAS Batch Process';

DATA work.report_data;
    SET raw.financial_transactions;
    WHERE fiscal_quarter = 1 AND fiscal_year = 2025;
RUN;

ODS PDF FILE='/output/q1_report.pdf';

PROC PRINT DATA=work.report_data NOOBS;
    VAR account_id transaction_date amount category;
RUN;

ODS PDF CLOSE;
TITLE;
FOOTNOTE;
